### PR TITLE
Biojs integration

### PR DESCRIPTION
**Pull request by jegalle**
Hi 

This implements biojs into the flavor generator. I've created tabs to seperate views.

You can see the changes in action here: http://galaxyflavorgenerator.biobix.be/

Let me know if you have any remarks

Gr. Jeroen

### CODE REVIEW

**Comment by bgruening** [comment]
@jegalle awesome. This is very user-friendly and looks superb!
On the backend side, please user 

```
RUN install-biojs msa
```

`install-biojs` will take care about the node installation and so on. It would be also good to combine all visualisations into one RUN command, so we save on Docker layer.

Your PR is not merge able currently, can you please rebase it against master?
@wookoouk do you want to review it? :)

Thanks this looks fantastic!
Bjoern

**Comment by doomedramen** [comment]
I am away from the office (and a machine that I can test the code from) right now (wifes in labor) but will have  a look asap. How are getting on with React @jegalle ? your coding like you have been using it for ages :)

**Comment by doomedramen** [comment]
The demo (http://galaxyflavorgenerator.biobix.be/) looks good, some visual stuff needs tweaking but works great.

**Comment by jegalle** [comment]
rebase gave some trouble so i forked again and copied over the changes (without doing 'gulp') and i am now ready to send a new pull request.

@bgruening: I've combined all visualisations in one docker command. But i did not find any information on 'install-biojs', where to get it from and such.  So atm it still uses biojs2galaxy to get it into the galaxy.

@wookoouk: First of all congratz! Second, i'm getting the hang of react, the code you already made helped me a lot already into understanding react. And ofcourse my good friend google. :)

**Comment by bgruening** [comment]
@wookoouk awesome! Congrats! Surely we want to have pictures :)
@jegalle `install-biojs` is a wrapper script shipped with the container, you can find it here: https://github.com/bgruening/docker-galaxy-stable/blob/master/galaxy/install_biojs_vis.sh

I will close this PR as soon as the new one is open.

**Comment by bgruening** [comment]
Closed in favour of https://github.com/galaxyFlavorsGenerators/galaxyFlavorGenerator/pull/20

**Pull request closed without merging**
